### ISSUE TITLE
Identify the files in the source required to compile it

### ISSUE THREAD

**Issue by LordGolias** [LordGolias/Brytenwalda#2]
What files from the source code are necessary to compile the source? Some files may not be required and therefore should not be added to git. Lets list them here.

Let's identify them from the version 23 of January 4th, found here: http://www.nexusmods.com/mbwarband/mods/5997/?tab=2

**Comment by gdwitt** [comment]
The process files know which ones to grab. Anything with an extension has been renamed for the sake of comparison. This helps with modding as you know what others have already done and where the changes have been made via programs like WinMerge.
If you want a list, I would first point to all the "header_xyz" files. Those are the files that contain definitions of the terms and shortcuts used in the module files. The header files that are surplus but still needed as imports are header_terraintypes, misstion_types, operations.
Module_info and module_variables don't have headers but are system information files that the game needs to compile. Variables seems to amend itself as you add new global trigger with $g. Module_info contains the compile directory where everything goes. You need this setup even before compiling.

Another way to look at it: see which ID files change their last changed date when you compile. Not every module file needs an ID file, but most of them do.

Notice there two compilers. 
The 2009 traditional version and LAV's WRECK version which is much faster. 

Finally, there's some loose files that are still in there from past work. If more people work on this, I guess I should remove them. Most of them come from plugins from various other modders that I attempted to implement. Right now they are fall back Plan B options in case current code is not seen as optimal by players.

**Comment by LordGolias** [comment]
Great. I meant mostly those loose files from past work. Those are not part of the source. I started to remove them in the version to add to git. You and I may keep them in our computer, but in git history is stored via commits, not via files of previous versions.

Other examples, that I'm not sure we are using at the moment:

1. a dir called "plugins".
2. a dir called "mapas", with 3 different versions (which one is being used, if any?)

**Comment by LordGolias** [comment]
The files `ID_*.py` are also not part of the source (I know, it seems odd). These files are created by the `process_*` for whatever reason that transcends me (and are them imported in other places, which is a WOW in Python). This is easily avoided by some Python code.

**Comment by gdwitt** [comment]
WRECK seems to ignore ID files. However, this becomes a problem when you add a new variable. The number of the ID seems important for the text files to recognize a new variable and increment up all the following variables.

**Comment by LordGolias** [comment]
I tried running WRECK (python -m compile) without the files ID_*, and it
fails asking for the files. So, at least it depends on them.

**Comment by LordGolias** [comment]
Closed by 03de6.
