### ISSUE TITLE
Shuffling formations

### ISSUE THREAD

**Issue by gdwitt** [LordGolias/Brytenwalda#23]
When groups form ranks or shieldwall, they starting moving at a sidewards angle towards the enemy even when I give the order "hold this position."
The only way I have to get them to stop is to say break formation or to tell them to move backwards 10 paces.
This is a distressing bug and I'm not sure the AI has the same problem.
My testing also shows that player parties in formation do very poorly versus enemies in formation or not in formation. They do very bad against enemies not in formation. Formations need a big boost somehow. 
Motomatura was the developer of the formation system and he has been very busy with the Viking Conquest project. I think he is an American programmer that is busy with a new project now (we communicated on Reddit). This was not an issue back in 2013 when I first started playing. If we have too little time for formations I would:
1) compare to 2013 Brytenwalda
2) Ask for help from other Brytenwalda mods and use their formation code. Produno and Idibil might be able to help.

**Comment by LordGolias** [comment]
Closing as duplicated of #22.
