### ISSUE TITLE
`slot_spy_in_town` collides with `dplmc_slot_party_mission_diplomacy`

### ISSUE THREAD

**Issue by LordGolias** [LordGolias/Brytenwalda#6]
While refactoring the `game_start` script, I found that `slot_spy_in_town`, used for tell how many spies a center currently has spying it, has the same slot number (300) as the slot `dplmc_slot_party_mission_diplomacy`, used in other situations. 

This may lead to unexpected behaviour and needs to be fixed.

Other potential conflicts between slots should also be checked!

**Comment by gdwitt** [comment]
This might be causing our bug with the spies deploying without choosing them to do so.
I would combine them. When you see "dplm" it means that someone just added it to the game without thinking about it much. The core modders removed most of the dplmc references.

**Comment by LordGolias** [comment]
What do you mean combine them?

AFAI understand, the issue with spies may be that when `dplmc_slot_party_mission_diplomacy` is modified, it automatically modifies the value of `slot_spy_in_town` because the slot number is the same, and they are both applied to parties (i.e. they are get/set via  )

The fast solution is to use a different a different slot number (i.e. 301 instead of 300) in one of them. 
The better solution is to implement a "checker" that checks that slots do not collide.
A even better solution is to implement a way of automatically assign numbers to slots in a way that avoids collisions.

**Comment by LordGolias** [comment]
Fixed in d0a1fca4209f23dc0ef56831958a101bc73b7143
