### ISSUE TITLE
War controversy between lords fills the message list and is not that important

### ISSUE THREAD

**Issue by LordGolias** [LordGolias/Brytenwalda#8]
Suggestion: make it to only appear in the game log, so the ingame messages are more related to the player.

**Comment by gdwitt** [comment]
I think I just uncommented the debug messages. This was very useful for trying to figure out why Lords were defecting from their kingdoms. It can be commented out for now as long as we know where to find it to uncomment in the future.

**Comment by gdwitt** [comment]
I would make this a level 2 debug. I want to see this pritn to the rgl_log when I somehow enter debug mode. Lords are still acting strangely and I never truly fixed the reasons they were defecting.
